### PR TITLE
Fix available codec check order

### PR DESCRIPTION
**Pull request by kou**
We need to check codec availability before calling new.

### CODE REVIEW

**Comment by kou** [comment]
We can create a zip file to reproduce this case by 7z:

```console
% 7z a x.zip archive-zip.gemspec -mm=LZMA
```

**Comment by javanthropus** [comment]
This change makes perfect sense.  I'll prepare a new release with it.

**Comment by javanthropus** [comment]
v0.12.0 is released with these changes.

**Comment by kou** [comment]
Wow! Thanks for your quick response!

**Pull request merged**
